CREATE TABLE IF NOT EXISTS "USER_MASTER" ("ID" TEXT PRIMARY KEY, "PASS" TEXT, "CUR_VER" DOUBLE);

CREATE TABLE IF NOT EXISTS "TBL_METERMASTER" (
"CONSUMERNO"			text PRIMARY KEY,
"OLDCONSUMERNO"	     	text,
"TARIFFCODE"	     	text,
"METERDEVICESERIALNO"	text,
"NAME"	             	text,
"ADDRESS"	         	text,
"CYCLE"	             	text,
"ROUTENO"	         	text,
"DIVISION"	         	text,
"SUBDIVISION"	     	text,
"SECTION"	         	text,
"BILLMONTH"	         	text,
"METERREADINGDATE"	 	text,
"CURRENTMETERSTATUS"	text,
"NORMALKWH"	         	text,
"NORMALKVAH"	     	text,
"NORMALKVARH"	     	text,
"NORMALMD"	         	text,
"NORMALMDUNIT"	     	text,
"PEAKKWH"	         	text,
"PEAKKVAH"	         	text,
"PEAKKHARH"	         	text,
"PEAKMD"	         	text,
"PEAKMDUNIT"	     	text,
"OFFPEAKKWH"	     	text,
"OFFPEAKKVAH"	     	text,
"OFFPEAKKHARH"	     	text,
"OFFPEAKMD"	         	text,
"OFFPEAKMDUNIT"	     	text,
"RIFLAG"             	text,
"OUTTERBOXSEAL" 		TEXT,
"INNERBOXSEAL" 			TEXT,
"OPTICALSEAL" 			TEXT,
"MDBUTTONSEAL" 			TEXT,
"CUMULATIVEMD" 			TEXT,
"KWH3CON" 				TEXT,
"KWH6CON" 				TEXT,
"MD3CON" 				TEXT,
"MD6CON" 				TEXT,
"OFFPEAK3CON" 			TEXT,
"OFFPEAK6CON" 			TEXT,
"MOB_NO" 				TEXT,
"EMAIL" 				TEXT,
"METER_REPLACE" 		TEXT,
"NSC" 				    TEXT,
"MF" 				    TEXT,
"KVAH3CON"              TEXT,
"KVAH6CON"              TEXT,
"LOAD"                  TEXT,
"LOADUNITS"             TEXT,
"METERDIGIT"            TEXT,
"DIVCODE"               TEXT,
"SUBDIVCODE"            TEXT,
"SECCODE"               TEXT,
"PANNO"                 TEXT,
"PREPAYMENT"            TEXT,
"CESUDIV"               TEXT,
"CESUSUBDIV"            TEXT,
"CESUSEC"               TEXT);


CREATE TABLE IF NOT EXISTS "TBL_METERUPLOAD" (
 "CONSUMERNO"          TEXT PRIMARY KEY,
 "OLDCONSUMERNO"       TEXT ,
 "TARIFFCODE"          TEXT ,
 "METERDEVICESERIALNO" TEXT ,
 "NAME"                TEXT ,
 "ADDRESS"             TEXT ,
 "CYCLE"               TEXT ,
 "ROUTENO"             TEXT ,
 "DIVISION"            TEXT ,
 "SUBDIVISION"         TEXT ,
 "SECTION"             TEXT ,
 "BILLMONTH"           TEXT ,
 "METERREADINGDATE"    TEXT ,
 "CURRENTMETERSTATUS"  TEXT ,
 "NORMALKWH"           TEXT ,
 "NORMALKVAH"          TEXT ,
 "NORMALKVARH"         TEXT ,
 "NORMALMD"            TEXT ,
 "NORMALMDUNIT"        TEXT ,
 "PEAKKWH"             TEXT ,
 "PEAKKVAH"            TEXT ,
 "PEAKKHARH"           TEXT ,
 "PEAKMD"              TEXT ,
 "PEAKMDUNIT"          TEXT ,
 "OFFPEAKKWH"          TEXT ,
 "OFFPEAKKVAH"         TEXT ,
 "OFFPEAKKHARH"        TEXT ,
 "OFFPEAKMD"           TEXT ,
 "OFFPEAKMDUNIT"       TEXT ,
 "RIFLAG"              TEXT ,
 "OUTTERBOXSEAL"       TEXT ,
 "INNERBOXSEAL"        TEXT ,
 "OPTICALSEAL"         TEXT ,
 "MDBUTTONSEAL"        TEXT ,
 "OLDOUTTERBOXSEAL"    TEXT ,
 "OLDINNERBOXSEAL"     TEXT ,
 "OLDOPTICALSEAL"      TEXT ,
 "OLDMDBUTTONSEAL"     TEXT ,
 "CUMULATIVEMD"        TEXT ,
 "KWH3CON"             TEXT ,
 "KWH6CON"             TEXT ,
 "MD3CON"              TEXT ,
 "MD6CON"              TEXT ,
 "OFFPEAK3CON"         TEXT ,
 "OFFPEAK6CON"         TEXT ,
 "MOB_NO"              TEXT ,
 "EMAIL"               TEXT ,
 "METERVOLTR"          TEXT ,
 "METERVOLTY"          TEXT ,
 "METERVOLTB"          TEXT ,
 "METERCURR"           TEXT ,
 "METERCURY"           TEXT ,
 "METERCURB"           TEXT ,
 "TONGUEVOLTR"         TEXT ,
 "TONGUEVOLTY"         TEXT ,
 "TONGUEVOLTB"         TEXT ,
 "TONGUECURR"          TEXT ,
 "TONGUECURY"          TEXT ,
 "TONGUECURB"          TEXT ,
 "UPLOADFLAG"          TEXT ,
 "IMAGE1"              TEXT ,
 "IMAGE2"              TEXT ,
 "USER_LONG"           TEXT ,
 "USER_LAT"            TEXT ,
 "BATERY_STAT"         TEXT ,
 "SIG_STRENGTH"        TEXT ,
 "GPS_TIME"            TEXT ,
 "PRINTER_BAT"         TEXT ,
 "VER_CODE"            TEXT ,
 "USER_ALT"            TEXT ,
 "USER_ACCURACY"       TEXT ,
 "REMARK"              TEXT ,
 "MR_CODE"             TEXT ,
 "CONSUMPKWH"          TEXT ,
 "CONSUMPKVAH"         TEXT ,
 "CONSUMPMD"           TEXT ,
 "CONSUMPOKWH"         TEXT ,
 "DIVCODE"             TEXT ,
 "SUBDIVCODE"          TEXT ,
 "SECCODE"             TEXT ,
 "FRESHDFFLAG"         TEXT ,
 "PANNO"               TEXT ,
 "CESUDIV"             TEXT ,
 "CESUSUBDIV"          TEXT ,
 "CESUSEC"             TEXT ,
 "METERREADDATE"       TEXT);

ALTER TABLE  "TBL_BILLING"  	ADD COLUMN   	"Mobile_no" 		TEXT DEFAULT NULL;
ALTER TABLE  "TBL_BILLING"  	ADD COLUMN   	"GPS_time" 			TEXT DEFAULT NULL;
ALTER TABLE  "TBL_BILLING"  	ADD COLUMN   	"Printer_bat" 		TEXT DEFAULT NULL;
ALTER TABLE  "TBL_BILLING"  	ADD COLUMN   	"Ver_code" 			TEXT DEFAULT NULL;
ALTER TABLE  "TBL_BILLING"  	ADD COLUMN   	"User_alt" 			TEXT DEFAULT NULL;
ALTER TABLE  "TBL_BILLING"  	ADD COLUMN   	"User_accuracy" 	TEXT DEFAULT NULL;

ALTER TABLE  "TBL_COLMASTER"  	ADD COLUMN  	"MOB_NO" 			TEXT DEFAULT NULL;
ALTER TABLE  "TBL_COLMASTER"  	ADD COLUMN  	"GPS_TIME" 			TEXT DEFAULT NULL;
ALTER TABLE  "TBL_COLMASTER"  	ADD COLUMN  	"PRINTER_BAT" 		TEXT DEFAULT NULL;
ALTER TABLE  "TBL_COLMASTER"  	ADD COLUMN  	"VER_CODE" 			TEXT DEFAULT NULL;
ALTER TABLE  "TBL_COLMASTER"  	ADD COLUMN  	"USER_ALT" 			TEXT DEFAULT NULL;
ALTER TABLE  "TBL_COLMASTER"  	ADD COLUMN  	"USER_ACCURACY" 	TEXT DEFAULT NULL;
