ALTER TABLE  "TBL_CONSUMERSURVEY_UPOLOAD"  	ADD COLUMN   	"CONN_TYP" 	        TEXT DEFAULT NULL;
ALTER TABLE  "TBL_CONSUMERSURVEY_UPOLOAD"  	ADD COLUMN   	"CON_CASTE" 	    TEXT DEFAULT NULL;
ALTER TABLE  "TBL_CONSUMERSURVEY_UPOLOAD"  	ADD COLUMN   	"CON_CONN_TYPE" 	TEXT DEFAULT NULL;
ALTER TABLE  "TBL_CONSUMERSURVEY_UPOLOAD"  	ADD COLUMN   	"NO_OF_ROOMS" 	    TEXT DEFAULT NULL;
ALTER TABLE  "TBL_CONSUMERSURVEY_UPOLOAD"  	ADD COLUMN   	"NO_OF_AC" 	        TEXT DEFAULT NULL;
ALTER TABLE  "TBL_CONSUMERSURVEY_UPOLOAD"  	ADD COLUMN   	"WATERPUMP_STS" 	TEXT DEFAULT NULL;
ALTER TABLE  "TBL_CONSUMERSURVEY_UPOLOAD"  	ADD COLUMN   	"NO_OF_COOLERS" 	TEXT DEFAULT NULL;

ALTER TABLE  "TBL_11KVFEEDER_UPLOAD"  	ADD COLUMN   "MF" 	            TEXT DEFAULT NULL;
ALTER TABLE  "TBL_11KVFEEDER_UPLOAD"  	ADD COLUMN   "CTR" 	            TEXT DEFAULT NULL;
ALTER TABLE  "TBL_11KVFEEDER_UPLOAD"  	ADD COLUMN   "PTR" 	            TEXT DEFAULT NULL;
ALTER TABLE  "TBL_11KVFEEDER_UPLOAD"  	ADD COLUMN   "DC" 	            TEXT DEFAULT NULL;
ALTER TABLE  "TBL_11KVFEEDER_UPLOAD"  	ADD COLUMN   "TAP_POINT"        TEXT DEFAULT NULL;
ALTER TABLE  "TBL_11KVFEEDER_UPLOAD"  	ADD COLUMN   "TAP_POINT_LAT"    TEXT DEFAULT NULL;
ALTER TABLE  "TBL_11KVFEEDER_UPLOAD"  	ADD COLUMN   "TAP_POINT_LONG"   TEXT DEFAULT NULL;
ALTER TABLE  "TBL_11KVFEEDER_UPLOAD"  	ADD COLUMN   "DC_CODE"          TEXT DEFAULT NULL;
ALTER TABLE  "TBL_11KVFEEDER_MASTER"  	ADD COLUMN   "TAP_POINT" 	    TEXT DEFAULT NULL;
ALTER TABLE  "TBL_DTR_UPLOAD"  	        ADD COLUMN   "DTR_DC" 	        TEXT DEFAULT NULL;
ALTER TABLE  "TBL_DTR_UPLOAD"  	        ADD COLUMN   "DTR_STS" 	        TEXT DEFAULT NULL;
ALTER TABLE  "TBL_POLE_MASTER"  	    ADD COLUMN   "DT_CODE" 	        TEXT DEFAULT NULL;
ALTER TABLE  "TBL_POLE_UPLOAD"  	    ADD COLUMN   "POLE_CON_COUNT" 	TEXT DEFAULT NULL;

ALTER TABLE  "TBL_CONSMAST"  	ADD COLUMN   	"AVGUNITS1" 	       TEXT DEFAULT NULL;
ALTER TABLE  "TBL_CONSMAST"  	ADD COLUMN   	"AVGUNITS2" 	       TEXT DEFAULT NULL;
ALTER TABLE  "TBL_CONSMAST"  	ADD COLUMN   	"AVGUNITS3" 	       TEXT DEFAULT NULL;
ALTER TABLE  "TBL_CONSMAST"  	ADD COLUMN   	"SYSTEM_FLAG" 	       TEXT DEFAULT NULL;
ALTER TABLE  "TBL_CONSMAST"  	ADD COLUMN   	"BILLED_FLAG" 	       TEXT DEFAULT 'N';
ALTER TABLE  "TBL_CONSMAST"  	ADD COLUMN   	"ONLINE_PYMT_REB" 	   TEXT DEFAULT NULL;
ALTER TABLE  "TBL_CONSMAST"  	ADD COLUMN   	"LST_ASSD" 	           TEXT DEFAULT NULL;
ALTER TABLE  "TBL_CONSMAST"  	ADD COLUMN   	"LST_2ND_ASSD" 	       TEXT DEFAULT NULL;
ALTER TABLE  "TBL_CONSMAST"  	ADD COLUMN   	"LST_3RD_ASSD" 	       TEXT DEFAULT NULL;

ALTER TABLE  "TBL_BILLING"  	ADD COLUMN   	"BILL_TYP_CD" 		   TEXT DEFAULT '4';
ALTER TABLE  "TBL_BILLING"  	ADD COLUMN   	"O_FCA_Flat_Subsidy"   TEXT ;
ALTER TABLE  "TBL_BILLING"  	ADD COLUMN   	"ACTUAL_READING" 	   TEXT ;
ALTER TABLE  "TBL_BILLING"  	ADD COLUMN   	"REASONS" 		       TEXT ;
ALTER TABLE  "TBL_BILLING"  	ADD COLUMN   	"IVRS_NO" 		       TEXT ;
ALTER TABLE  "TBL_BILLING"  	ADD COLUMN   	"MBC_CONSUMPTION" 		TEXT ;
ALTER TABLE  "TBL_BILLING"  	ADD COLUMN   	"TOTAL_CONSUMPTION" 		TEXT ;
ALTER TABLE  "TBL_BILLING"  	ADD COLUMN   	"APP1_CONSUMPTION" 		TEXT ;
ALTER TABLE  "TBL_BILLING"  	ADD COLUMN   	"APP1_NAME" 		TEXT ;
ALTER TABLE  "TBL_BILLING"  	ADD COLUMN   	"APP2_CONSUMPTION" 		TEXT ;
ALTER TABLE  "TBL_BILLING"  	ADD COLUMN   	"APP2_NAME" 		TEXT ;
ALTER TABLE  "TBL_BILLING"  	ADD COLUMN   	"APP3_CONSUMPTION" 		TEXT ;
ALTER TABLE  "TBL_BILLING"  	ADD COLUMN   	"APP3_CONSUMPTION" 		TEXT ;
ALTER TABLE  "TBL_BILLING"  	ADD COLUMN   	"EMAIL_ID" 		TEXT ;
ALTER TABLE  "TBL_BILLING"  	ADD COLUMN   	"METER_NUMBER" 		TEXT ;

ALTER TABLE  "TBL_COLLECTION"  	ADD COLUMN   	"MOB_NO" 		TEXT ;
ALTER TABLE  "TBL_COLLECTION"  	ADD COLUMN   	"IVRS_NO" 		TEXT ;
ALTER TABLE  "TBL_COLLECTION"  	ADD COLUMN   	"LOC_CD" 		TEXT ;
ALTER TABLE  "TBL_COLLECTION"  	ADD COLUMN   	"BILL_MON" 		TEXT ;

ALTER TABLE  "USER_MASTER"  	ADD COLUMN   	"PRINTER_PREF" 		TEXT  DEFAULT "0_0_1";

ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"TARIFF_TO_DATE" 	 	     TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"LOAD_MIN" 	 		 	     TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"LOAD_MAX" 	 		 	     TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"LOAD_UNIT" 	 	 	     TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"SUBSIDY_FLAG" 	 	 	     TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"FLAT_RATE_FLAG" 	 	     TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"SEASON_FLAG" 	 	 	     TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MIN_CHARGE_RATE_FLAG" 	     TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MIN_CHARGE_UNIT" 	         TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MIN_URBAN_CHARGES_H1_3ph" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MIN_RURAL_CHARGES_H1_3ph" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MIN_URBAN_CHARGES_H1_1PH" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MIN_RURAL_CHARGES_H1_1PH" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MIN_URBAN_CHARGES_H2_3PH" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MIN_RURAL_CHARGES_H2_3PH" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MIN_URBAN_CHARGES_H2_1PH" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MIN_RURAL_CHARGES_H2_1PH" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MIN_URBAN_CD_UNIT" 	     TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MIN_RURAL_CD_UNIT" 	     TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MIN_CHARGE_MIN_CD" 	     TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"FREE_MIN_FOR_MONTHS" 	     TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"OTHER_CHARGE_FLAG" 	     TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"Below_30_DOM_MIN_CD_KW_EC" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"Below30_DOM_EC_Unit" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"Below30_DOM_EC_CHG" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"EC_SLAB_1" 	     TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"EC_SLAB_2" 	     TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"EC_SLAB_3" 	     TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"EC_SLAB_4" 	     TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"EC_SLAB_5" 	     TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"EC_URBAN_RATE_1" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"EC_URBAN_RATE_2" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"EC_URBAN_RATE_3" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"EC_URBAN_RATE_4" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"EC_URBAN_RATE_5" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"EC_RURAL_RATE_1" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"EC_RURAL_RATE_2" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"EC_RURAL_RATE_3" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"EC_RURAL_RATE_4" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"EC_RURAL_RATE_5" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"EC_UNIT" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"Below_30_DOM_MIN_CD_KW_MFC" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"Below30_DOM_MFC_Unit" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"Below30_DOM_MFC_CHG" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MMFC_SLAB_1" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MMFC_SLAB_2" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MMFC_SLAB_3" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MMFC_SLAB_4" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MMFC_SLAB_5" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MD_MFC_CMP_FLAG" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"Rate_UNIT_MFC" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"KWh_CON_KW_Flag" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"KWh_CON_KW" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MMFC_KVA_FLAG_SLAB_1" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MMFC_KVA_FLAG_SLAB_2" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MMFC_KVA_FLAG_SLAB_3" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MMFC_KVA_FLAG_SLAB_4" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MMFC_KVA_FLAG_SLAB_5" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MMFC_URBAN_RATE_1" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MMFC_URBAN_RATE_2" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MMFC_URBAN_RATE_3" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MMFC_URBAN_RATE_4" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MMFC_URBAN_RATE_5" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MMFC_RURAL_RATE_1" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MMFC_RURAL_RATE_2" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MMFC_RURAL_RATE_3" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MMFC_RURAL_RATE_4" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MMFC_RURAL_RATE_5" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ADDNL_FIXED_CHARGE_1PH" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ADDNL_FIXED_CHARGE_3PH" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"FLAG_BPL_SUBSIDY_CODE" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"FLAG_EC_MFC" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MFC_SUBSIDY_FLAT" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"FCA_SUBSIDY_FLAT" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"SUBSIDY_UNITS_SLAB_1" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"SUBSIDY_UNITS_SLAB_2" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"SUBSIDY_UNITS_SLAB_3" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"SUBSIDY_UNITS_SLAB_4" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"SUBSIDY_UNITS_SLAB_5" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"SUBSIDY_UNITS_SLAB_6" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"SUBSIDY_RATE_1" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"SUBSIDY_RATE_2" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"SUBSIDY_RATE_3" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"SUBSIDY_RATE_4" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"SUBSIDY_RATE_5" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"SUBSIDY_RATE_6" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"Below_30_DOM_MIN_CD_KW_ED" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"Below30_DOM_ED_Unit" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"Below30_DOM_ED_CHG" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"Below30_DOM_ED_CHG_Rate" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ED_UNITS_SLAB_1" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ED_UNITS_SLAB_2" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ED_UNITS_SLAB_3" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ED_UNITS_SLAB_4" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ED_UNITS_SLAB_5" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ED_URBAN_RATE_1" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ED_URBAN_RATE_2" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ED_URBAN_RATE_3" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ED_URBAN_RATE_4" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ED_URBAN_RATE_5" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ED_RURAL_RATE_1" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ED_RURAL_RATE_2" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ED_RURAL_RATE_3" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ED_RURAL_RATE_4" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ED_RURAL_RATE_5" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ED_PER_RATE_1" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ED_PER_RATE_2" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ED_PER_RATE_3" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ED_PER_RATE_4" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ED_PER_RATE_5" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"FCA_Q1" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"FCA_Q2" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"FCA_Q3" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"FCA_Q4" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"PREPAID_REBATE" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ISI_INC_FLAG" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ISI_MOTOR_INCENTIVE_TYPE_1" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ISI_MOTOR_INCENTIVE_TYPE_2" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ISI_MOTOR_INCENTIVE_TYPE_3" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MIN_DPS_BILL_AMT" 	         TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"DPS_MIN_AMT_Below_500" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"DPS_MIN_AMT_Above_500" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"DPS_FLAG_PERCENTAGE" 	     TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"DPS" 	                     TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ADV_PAY_REBATE_PERCENT" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"INC_PMPT_PAY_PERCENT" 	     TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"OL_REBATE_PERCENT" 	     TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"LF_INC_SLAB_1" 	         TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"LF_INC_SLAB_2" 	         TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"LF_INC_SLAB_3" 	         TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"LF_INC_RATE_1" 	         TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"LF_INC_RATE_2" 	         TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"LF_INC_RATE_3" 	         TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"PF_INC_SLAB_1" 	         TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"PF_INC_SLAB_2" 	         TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"PF_INC_RATE_1" 	         TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"PF_INC_RATE_2" 	         TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"PF_PEN_SLAB_1" 	         TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"PF_PEN_SLAB_2" 	         TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"PF_PEN_RATE_1" 	         TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"PF_PEN_RATE_2" 	         TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"PF_PEN_SLAB2_ADDL_PERCENT" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"PF_PEN_MAX_CAP_PER" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"WL_SLAB" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"WL_RATE" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"Emp_Rebate" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"FLG_FIXED_UNIT_SUBSIDY" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"Overdrawl_Slab1" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"Overdrawl_Slab2" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"Overdrawl_Slab3" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"Overdrawl_Rate1" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"Overdrawl_Rate2" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"Overdrawl_Rate3" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"EC_Flag" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"ED_Flag" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"Tariff_URBAN" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"Tariff_RURAL" 	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"MAX_ALLOWABLE_CONSUMPTION"	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"PF_APPLICABLE"	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"PF_INC_APPLICABLE"	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"CAP_CHRG_APPLICABLE"	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"FULL_SUBSIDY_FLAG"	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"IND_VALIDATION"	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"BPL_VALIDATION"	 TEXT DEFAULT NULL;
ALTER TABLE  "TBL_TARRIF_MP"  	ADD COLUMN   	"JBP_VALIDATION"	 TEXT DEFAULT NULL;

UPDATE "TBL_METERSTATUSCODE_MP" SET STATUS ='PREMISES LOCKED' WHERE STATE_ID='2';

CREATE TABLE IF NOT EXISTS "TBL_BILLING_DC_MASTER"
(
  "SUB_DIV_CODE" 			    TEXT,
  "SEC_CODE" 				    TEXT,
  "SEC_NAME" 				    TEXT,
  "DISPLAY_CODE" 			    TEXT,
  "CESU_DIV_CODE" 			    TEXT,
  "CESU_SUB_DIV_CODE" 		    TEXT,
  "CESU_SEC_CODE" 			    TEXT,
  "RMS_DC_CODE" 	            TEXT,
  "CCNB_DC_CODE" 	            TEXT
);

ALTER TABLE  "TBL_BILLING_DC_MASTER"  	ADD COLUMN   	"FULL_SUBSIDY_FLAG"	 TEXT DEFAULT NULL;

CREATE TABLE IF NOT EXISTS "TBL_BILLING_DIV_MASTER"
(
  "CIRCLE_CODE"  		        TEXT,
  "DIVISION_CODE"   	        TEXT,
  "DIV_NAME"  			        TEXT,
  "DISPLAY_CODE"  		        TEXT,
  "CENTER_NAME"  		        TEXT,
  "UTILITY_NAME"  		        TEXT
);

--ALTER TABLE  "TBL_BILLING_DIV_MASTER"  	ADD COLUMN   	"PRO_CODE"	 TEXT DEFAULT NULL;

CREATE TABLE IF NOT EXISTS "TBL_REMARKS_MASTER"
(
  "SR_NO"  		            TEXT,
  "SRNO"  		            TEXT,
  "REMARK_DESC"   	        TEXT,
  "BILL_BASIS"  			TEXT
);

DROP TABLE IF EXISTS "TBL_TARIFF_SYBASE";
CREATE TABLE "TBL_TARIFF_SYBASE" ("SYBASE_CODE"  NOT NULL , "TARIFF_DESCRIPTION" , "RMS_CODE" NOT NULL);

INSERT INTO "TBL_TARIFF_SYBASE" VALUES('101','Domestic L&F , Power (1 Phase)','101');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('102','Non Domestic L&F, Power (1 Ph)','102');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('103','Non Domestic L&F,Power (3 Ph)','102');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('104','Domestic DTR METERED','104');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('105','Non Domestic (EDUCATIONAL INST','204');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('106','Non Domestic TWO PART','205');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('107','Domestic L&F, Power (3 Phase)','101');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('108','Domestic Temp.(OWN HOUSE CONST','901');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('109','Non Domestic Temp. MELA etc','902');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('110','Dom Employee L&F,Power (1 Ph)','101');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('111','Dom Employee L&F, Power (3 Ph)','101');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('112','Dom Pensioner L&F,Power (1 Ph)','101');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('113','Dom Pensioner L&F,Power (3 Ph)','101');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('114','Dom.Unmetered SC/ST BPL','110');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('115','Dom.Unmetered General','111');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('116','Dom.  Metered SC/ST BPL','112');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('117','Non Domestic TWO PART EDU.INST','206');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('118','Non Domestic TELECOM (RURAL)','102');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('119','Non Dom.TWO PART TELECOM RURAL','205');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('120','Domestic Temp.(MARRIAGE/RELIGI','903');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('121','Non Dom.Temp.(MARRIAGE GARDENS','904');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('122','Domestic Temp.(OTHERS)','901');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('123','Non Dom.Temp.(OTHERS)','902');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('201','X-Ray Plants Single Phase','201');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('202','X-Ray Plants Three  Phase','201');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('203','X-Ray Plants 100 TO 150 BHP','203');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('301','Other Agriculture LV5.3','351');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('302','Single Phase AgrPump only(Ben)','306');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('303','Agriculture DTR METERED','303');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('304','Agriculture Flat Rate 1 PHASE','311');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('305','Alt-2 Power Agri.Met. LV5.1','305');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('306','Alt-2 Power for Agr Inst (Ben)','306');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('307','Agriculture Flat Rate 3 PHASE','313');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('308','Agri. Power 3 PHASE Flat (Ben)','320');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('309','Agriculture Metered Temporary','915');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('310','Agriculture Flat Rate 3 PH.Tem','916');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('311','Agriculture Flat Rate 1 PH.Tem','916');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('312','Agri. Power 1 PH.Flat (Ben)','319');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('313','Other Agriculture LV 5.2','341');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('401','L&F, Power Industries >0-10BHP','551');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('403','L&F, Power For Ind(S) >0-10BHP','551');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('404','L&F ,Power Industries >0-10BHP','551');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('406','L&F ,Power For Ind(S) >0-10BHP','551');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('407','L&F,Power Industries >10-25BHP','551');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('408','L&F, Power For Ind(S) >10-25HP','551');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('501','Industries TWO PART SEAS. KW','571');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('503','Industries TWO PART SEAS. KVA','571');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('601','Industries TWO PART <=100HP KW','571');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('603','Indus. TWO PART >100-150HP KW','581');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('701','Industrial Temp. 0-20 BHP','599');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('702','Industrial Temp. > 20 BHP','599');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('703','Indus. TWO PART >100-150HP KVA','581');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('801','MC/Cantt.WaterWorks upto150BHP','811');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('802','Pow WaterWorks&Sew >100-150BHP','811');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('803','L&F in Power Loom >0-10BHP','550');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('804','Industries TWO PART<=100HP KVA','571');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('805','PowerLoom Industries>10-25 BHP','550');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('806','Water Works MC-Cantt. Temporar','611');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('807','Oth.Agriculture TWO PART (KW)','353');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('808','Power Loom Industries>10-25BHP','550');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('809','Municipality/N Pan.WW>0-150BHP','812');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('810','Gram Pan.WaterWorks upto150BHP','813');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('811','MC/Cantt.Street Light>0-150BHP','611');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('812','Municipality/N Pan.SL>0-150BHP','612');
INSERT INTO "TBL_TARIFF_SYBASE" VALUES('813','Gram Pan.Street Light>0-150BHP','613');

CREATE TABLE IF NOT EXISTS "TBL_BANK_MASTER" (
"BANK_CODE" 			TEXT,
"BANK_NAME" 			TEXT,
"BRANCH_CODE" 			TEXT,
"BRANCH_NAME" 			TEXT,
"DIV_CODE" 			    TEXT);

CREATE TABLE IF NOT EXISTS "TBL_SESSION_MASTER" (
"MR_ID" 			TEXT,
"SESSION_ID" 		LONG,
"START_DATE" 		TEXT,
"END_DATE" 			TEXT,
"FLAG" 			    TEXT);

CREATE TABLE IF NOT EXISTS "TBL_METER_REPLACEMENT"
(
"CONSUMERNO" TEXT,
"IVRS_NO" TEXT,
"LOCCD" TEXT,
"REPLACEMENT_DATE" TEXT,
"REPLACEMENT_TIME" TEXT,
"OLD_METER_NO" TEXT,
"OLD_METER_MAKE" TEXT,
"OLD_METER_TYPE" TEXT,
"OLD_METER_CAPACITY" TEXT,
"OLD_METER_PHASE" TEXT,
"OLD_METER_FINAL_READING" TEXT,
"OLD_METER_OUTERBOX_SEAL" TEXT,
"OLD_METER_INNERBOX_SEAL" TEXT,
"OLD_METER_OPTICAL_SEAL" TEXT,
"OLD_METER_MDRESET_BUTTON_SEAL" TEXT,
"OLD_METER_BODY_SEAL" TEXT,
"OLD_METER_IMAGE_NAME" TEXT,
"NEW_METER_NO" TEXT,
"NEW_METER_MAKE" TEXT,
"NEW_METER_TYPE" TEXT,
"NEW_METER_CAPACITY" TEXT,
"NEW_METER_PHASE" TEXT,
"NEW_METER_FINAL_READING" TEXT,
"NEW_METER_OUTERBOX_SEAL" TEXT,
"NEW_METER_INNERBOX_SEAL" TEXT,
"NEW_METER_OPTICAL_SEAL" TEXT,
"NEW_METER_MDRESET_BUTTON_SEAL" TEXT,
"NEW_METER_BODY_SEAL" TEXT,
"NEW_METER_IMAGE_NAME" TEXT,
"LONGITUDE" TEXT,
"LATITUDE" TEXT,
"ALTITUDE" TEXT,
"ACCURACY" TEXT,
"BATTERYSTATUS" TEXT,
"SIGNALSTRENGTH" TEXT,
"VERSIONCODE" TEXT,
"GPSTIME" TEXT,
"MOBILENUMBER" TEXT,
"UPLOADFLAG" TEXT
);

CREATE TABLE IF NOT EXISTS "TBL_PASSWORD_MASTER" (
"MR_ID" 			TEXT,
"PASSWORD" 		    TEXT);