package com.fedco.mbc.model;

public class Structtariff {
    public static String ID                          ;
    public static String LOAD                        ;
    public static String LT                          ;
    public static String CATEGORY                    ;
    public static String SHORTCODE                   ;
    public static String DESCRIPTION                 ;
    public static Double MINLOAD                    = 0d  ;
    public static Double MAXLOAD                    = 0d  ;
    public static Double PHASE                      = 0d  ;
    public static Double MMFCFIRSTKW                = 0d  ;
    public static Double MMFCNEXTKW                 = 0d  ;
    public static Double EDRATE                     = 0d  ;
    public static Double ED_CAP                     = 0d  ;
    public static Double RBT_PER                    = 0d  ;
    public static Double MAXTIMES                   = 0d  ;
    public static Double MAXRS                      = 0d  ;
    public static Double DPS                        = 0d  ;
    public static Double CSC                        = 0d  ;
    public static Double LFSLAB1                    = 0d  ;
    public static Double LFRATE1                    = 0d  ;
    public static Double LFSLAB2                    = 0d  ;
    public static Double LFRATE2                    = 0d  ;
    public static Double ECSLAB1                    = 0d  ;
    public static Double ECRATE1                    = 0d  ;
    public static Double ECSLAB2                    = 0d  ;
    public static Double ECRATE2                    = 0d  ;
    public static Double ECSLAB3                    = 0d  ;
    public static Double ECRATE3                    = 0d  ;
    public static Double ECSLAB4                    = 0d  ;
    public static Double ECRATE4                    = 0d  ;
    public static Double INCPROMPTPAY               = 0d  ;
    public static Double OYTREBATE                  = 0d  ;
    public static Double TOD_INCETIVE               = 0d  ;
    public static Double PFSLAB1                    = 0d  ;
    public static Double PFRATE1                    = 0d  ;
    public static Double PFSLAB2                    = 0d  ;
    public static Double PFRATE2                    = 0d  ;
    public static Double PFSLAB3                    = 0d  ;
    public static Double PFRATE3                    = 0d  ;
    public static Double OVERDRAWLPENALTY           = 0d  ;
    public static Double OVERDRAWLPENALTYOFFPEAK    = 0d  ;
    public static Double REBATE_SC                  = 0d  ;
    public static Double REBATE_SD                  = 0d  ;
    public static String MDUNITS                     ;
    public static int	 AVGMONTHS                   ;
    public static String FROMDATE                    ;
    public static String TODATE                      ;
    public static Float  PF_INCENTIVE                ;
    public static String DEMAND_CHARGEFLG            ;
    public static Float  REL_SURCHARGE               ;

    //MP
    public static String TARIFF_CODE            ;
    public static String TARIFF_DESCRIPTION      ;
    public static String EFFECTIVE_DATE          ;
    public static String TARIFF_TO_DATE           ;
    public static Double LOAD_MIN= 0d  ;
    public static Double LOAD_MAX= 0d  ;
    public static String LOAD_UNIT ;
    public static String SUBSIDY_FLAG  ;
    public static String FLAT_RATE_FLAG ;
    public static String SEASON_FLAG;
    public static String MIN_CHARGE_RATE_FLAG  ;
    public static String MIN_CHARGE_UNIT ;
    public static Double MIN_URBAN_CHARGES_H1_3ph= 0d  ;
    public static Double MIN_RURAL_CHARGES_H1_3ph= 0d  ;
    public static Double MIN_URBAN_CHARGES_H1_1PH= 0d  ;
    public static Double MIN_RURAL_CHARGES_H1_1PH= 0d  ;
    public static Double MIN_URBAN_CHARGES_H2_3PH= 0d  ;
    public static Double MIN_RURAL_CHARGES_H2_3PH= 0d  ;
    public static Double MIN_URBAN_CHARGES_H2_1PH= 0d  ;
    public static Double MIN_RURAL_CHARGES_H2_1PH= 0d  ;
    public static Double MIN_URBAN_CD_UNIT= 0d  ;
    public static Double MIN_RURAL_CD_UNIT= 0d  ;
    public static Double MIN_CHARGE_MIN_CD= 0d  ;
    public static Double FREE_MIN_FOR_MONTHS= 0d  ;
    public static String OTHER_CHARGE_FLAG ;
    public static Double Below_30_DOM_MIN_CD_KW_EC= 0d  ;
    public static Double Below30_DOM_EC_Unit= 0d  ;
    public static Double Below30_DOM_EC_CHG= 0d  ;
    public static Double EC_SLAB_1= 0d  ;
    public static Double EC_SLAB_2= 0d  ;
    public static Double EC_SLAB_3= 0d  ;
    public static Double EC_SLAB_4= 0d  ;
    public static Double EC_SLAB_5= 0d  ;
    public static Double EC_URBAN_RATE_1= 0d  ;
    public static Double EC_URBAN_RATE_2= 0d  ;
    public static Double EC_URBAN_RATE_3= 0d  ;
    public static Double EC_URBAN_RATE_4= 0d  ;
    public static Double EC_URBAN_RATE_5= 0d  ;
    public static Double EC_RURAL_RATE_1= 0d  ;
    public static Double EC_RURAL_RATE_2= 0d  ;
    public static Double EC_RURAL_RATE_3= 0d  ;
    public static Double EC_RURAL_RATE_4= 0d  ;
    public static Double EC_RURAL_RATE_5= 0d  ;
    public static String EC_UNIT ;
    public static Double Below_30_DOM_MIN_CD_KW_MFC= 0d  ;
    public static Double Below30_DOM_MFC_Unit= 0d  ;
    public static Double Below30_DOM_MFC_CHG = 0d  ;
    public static Double MMFC_SLAB_1= 0d  ;
    public static Double MMFC_SLAB_2= 0d  ;
    public static Double MMFC_SLAB_3= 0d  ;
    public static Double MMFC_SLAB_4= 0d  ;
    public static Double MMFC_SLAB_5= 0d  ;
    public static String MD_MFC_CMP_FLAG  ;
    public static String Rate_UNIT_MFC ;
    public static String KWh_CON_KW_Flag  ;
    public static Double KWh_CON_KW= 0d  ;
    public static String MMFC_KVA_FLAG_SLAB_1 ;
    public static String MMFC_KVA_FLAG_SLAB_2 ;
    public static String MMFC_KVA_FLAG_SLAB_3 ;
    public static String MMFC_KVA_FLAG_SLAB_4 ;
    public static String MMFC_KVA_FLAG_SLAB_5 ;
    public static Double MMFC_URBAN_RATE_1= 0d  ;
    public static Double MMFC_URBAN_RATE_2= 0d  ;
    public static Double MMFC_URBAN_RATE_3= 0d  ;
    public static Double MMFC_URBAN_RATE_4= 0d  ;
    public static Double MMFC_URBAN_RATE_5= 0d  ;
    public static Double MMFC_RURAL_RATE_1= 0d  ;
    public static Double MMFC_RURAL_RATE_2= 0d  ;
    public static Double MMFC_RURAL_RATE_3= 0d  ;
    public static Double MMFC_RURAL_RATE_4= 0d  ;
    public static Double MMFC_RURAL_RATE_5= 0d  ;
    public static Double ADDNL_FIXED_CHARGE_1PH= 0d  ;
    public static Double ADDNL_FIXED_CHARGE_3PH= 0d  ;
    public static String FLAG_BPL_SUBSIDY_CODE  ;
    public static String FLAG_EC_MFC  ;
    public static Double MFC_SUBSIDY_FLAT= 0d  ;
    public static String FCA_SUBSIDY_FLAT;
    public static Double SUBSIDY_UNITS_SLAB_1= 0d  ;
    public static Double SUBSIDY_UNITS_SLAB_2= 0d  ;
    public static Double SUBSIDY_UNITS_SLAB_3= 0d  ;
    public static Double SUBSIDY_UNITS_SLAB_4= 0d  ;
    public static Double SUBSIDY_UNITS_SLAB_5= 0d  ;
    public static Double SUBSIDY_UNITS_SLAB_6= 0d  ;
    public static Double SUBSIDY_RATE_1 = 0d  ;
    public static Double SUBSIDY_RATE_2 = 0d  ;
    public static Double SUBSIDY_RATE_3 = 0d  ;
    public static Double SUBSIDY_RATE_4 = 0d  ;
    public static Double SUBSIDY_RATE_5 = 0d  ;
    public static Double SUBSIDY_RATE_6 = 0d  ;
    public static Double Below_30_DOM_MIN_CD_KW_ED= 0d  ;
    public static Double Below30_DOM_ED_Unit= 0d  ;
    public static Double Below30_DOM_ED_CHG= 0d  ;
    public static Double Below30_DOM_ED_CHG_Rate= 0d  ;
    public static Double ED_UNITS_SLAB_1= 0d  ;
    public static Double ED_UNITS_SLAB_2= 0d  ;
    public static Double ED_UNITS_SLAB_3= 0d  ;
    public static Double ED_UNITS_SLAB_4= 0d  ;
    public static Double ED_UNITS_SLAB_5= 0d  ;
    public static Double ED_URBAN_RATE_1= 0d  ;
    public static Double ED_URBAN_RATE_2= 0d  ;
    public static Double ED_URBAN_RATE_3= 0d  ;
    public static Double ED_URBAN_RATE_4= 0d  ;
    public static Double ED_URBAN_RATE_5= 0d  ;
    public static Double ED_RURAL_RATE_1= 0d  ;
    public static Double ED_RURAL_RATE_2= 0d  ;
    public static Double ED_RURAL_RATE_3= 0d  ;
    public static Double ED_RURAL_RATE_4= 0d  ;
    public static Double ED_RURAL_RATE_5= 0d  ;
    public static Double ED_PER_RATE_1= 0d  ;
    public static Double ED_PER_RATE_2= 0d  ;
    public static Double ED_PER_RATE_3= 0d  ;
    public static Double ED_PER_RATE_4= 0d  ;
    public static Double ED_PER_RATE_5= 0d  ;
    public static Double FCA_Q1= 0d  ;
    public static Double FCA_Q2= 0d  ;
    public static Double FCA_Q3= 0d  ;
    public static Double FCA_Q4= 0d  ;
    public static Double PREPAID_REBATE= 0d  ;
    public static Double ISI_INC_FLAG= 0d  ;
    public static Double ISI_MOTOR_INCENTIVE_TYPE_1= 0d  ;
    public static Double ISI_MOTOR_INCENTIVE_TYPE_2= 0d  ;
    public static Double ISI_MOTOR_INCENTIVE_TYPE_3= 0d  ;
    public static Double MIN_DPS_BILL_AMT= 0d  ;
    public static Double DPS_MIN_AMT_Below_500= 0d  ;
    public static Double DPS_MIN_AMT_Above_500= 0d  ;
    public static String DPS_FLAG_PERCENTAGE ;
    public static Double DPS_MP= 0d  ;
    public static Double ADV_PAY_REBATE_PERCENT= 0d  ;
    public static Double INC_PMPT_PAY_PERCENT= 0d  ;
    public static Double OL_REBATE_PERCENT= 0d  ;
    public static Double LF_INC_SLAB_1= 0d  ;
    public static Double LF_INC_SLAB_2= 0d  ;
    public static Double LF_INC_SLAB_3= 0d  ;
    public static Double LF_INC_RATE_1= 0d  ;
    public static Double LF_INC_RATE_2= 0d  ;
    public static Double LF_INC_RATE_3= 0d  ;
    public static Double PF_INC_SLAB_1= 0d  ;
    public static Double PF_INC_SLAB_2= 0d  ;
    public static Double PF_INC_RATE_1= 0d  ;
    public static Double PF_INC_RATE_2= 0d  ;
    public static Double PF_PEN_SLAB_1= 0d  ;
    public static Double PF_PEN_SLAB_2= 0d  ;
    public static Double PF_PEN_RATE_1= 0d  ;
    public static Double PF_PEN_RATE_2= 0d  ;
    public static Double PF_PEN_SLAB2_ADDL_PERCENT= 0d  ;
    public static Double PF_PEN_MAX_CAP_PER= 0d  ;
    public static Double WL_SLAB= 0d  ;
    public static Double WL_RATE= 0d  ;
    public static Double Emp_Rebate= 0d  ;
    public static String FLG_FIXED_UNIT_SUBSIDY ;
    public static Double Overdrawl_Slab1 =0d  ;
    public static Double Overdrawl_Slab2 =0d   ;
    public static Double Overdrawl_Slab3 =0d   ;
    public static Double Overdrawl_Rate1 =0d   ;
    public static Double Overdrawl_Rate2 =0d   ;
    public static Double Overdrawl_Rate3 =0d   ;
    public static String EC_Flag           ;
    public static String ED_Flag           ;
    public static String Tariff_URBAN           ;
    public static String Tariff_RURAL           ;
    public static String MAX_ALLOWABLE_CONSUMPTION           ;
    public static String PF_APPLICABLE           ;
    public static String PF_INC_APPLICABLE           ;
    public static String CAP_CHRG_APPLICABLE           ;
    public static String FULL_SUBSIDY_FLAG           ;
    public static String IND_VALIDATION          ;
    public static String BPL_VALIDATION          ;
    public static String JBP_VALIDATION          ;


    //MP
    public static String OLD_TARIFF_CODE            ;
    public static String OLD_TARIFF_DESCRIPTION      ;
    public static String OLD_EFFECTIVE_DATE          ;
    public static String OLD_TARIFF_TO_DATE           ;
    public static Double OLD_LOAD_MIN= 0d  ;
    public static Double OLD_LOAD_MAX= 0d  ;
    public static String OLD_LOAD_UNIT ;
    public static String OLD_SUBSIDY_FLAG  ;
    public static String OLD_FLAT_RATE_FLAG ;
    public static String OLD_SEASON_FLAG;
    public static String OLD_MIN_CHARGE_RATE_FLAG  ;
    public static String OLD_MIN_CHARGE_UNIT ;
    public static Double OLD_MIN_URBAN_CHARGES_H1_3ph= 0d  ;
    public static Double OLD_MIN_RURAL_CHARGES_H1_3ph= 0d  ;
    public static Double OLD_MIN_URBAN_CHARGES_H1_1PH= 0d  ;
    public static Double OLD_MIN_RURAL_CHARGES_H1_1PH= 0d  ;
    public static Double OLD_MIN_URBAN_CHARGES_H2_3PH= 0d  ;
    public static Double OLD_MIN_RURAL_CHARGES_H2_3PH= 0d  ;
    public static Double OLD_MIN_URBAN_CHARGES_H2_1PH= 0d  ;
    public static Double OLD_MIN_RURAL_CHARGES_H2_1PH= 0d  ;
    public static Double OLD_MIN_URBAN_CD_UNIT= 0d  ;
    public static Double OLD_MIN_RURAL_CD_UNIT= 0d  ;
    public static Double OLD_MIN_CHARGE_MIN_CD= 0d  ;
    public static Double OLD_FREE_MIN_FOR_MONTHS= 0d  ;
    public static String OLD_OTHER_CHARGE_FLAG ;
    public static Double OLD_Below_30_DOM_MIN_CD_KW_EC= 0d  ;
    public static Double OLD_Below30_DOM_EC_Unit= 0d  ;
    public static Double OLD_Below30_DOM_EC_CHG= 0d  ;
    public static Double OLD_EC_SLAB_1= 0d  ;
    public static Double OLD_EC_SLAB_2= 0d  ;
    public static Double OLD_EC_SLAB_3= 0d  ;
    public static Double OLD_EC_SLAB_4= 0d  ;
    public static Double OLD_EC_SLAB_5= 0d  ;
    public static Double OLD_EC_URBAN_RATE_1= 0d  ;
    public static Double OLD_EC_URBAN_RATE_2= 0d  ;
    public static Double OLD_EC_URBAN_RATE_3= 0d  ;
    public static Double OLD_EC_URBAN_RATE_4= 0d  ;
    public static Double OLD_EC_URBAN_RATE_5= 0d  ;
    public static Double OLD_EC_RURAL_RATE_1= 0d  ;
    public static Double OLD_EC_RURAL_RATE_2= 0d  ;
    public static Double OLD_EC_RURAL_RATE_3= 0d  ;
    public static Double OLD_EC_RURAL_RATE_4= 0d  ;
    public static Double OLD_EC_RURAL_RATE_5= 0d  ;
    public static String OLD_EC_UNIT ;
    public static Double OLD_Below_30_DOM_MIN_CD_KW_MFC= 0d  ;
    public static Double OLD_Below30_DOM_MFC_Unit= 0d  ;
    public static Double OLD_Below30_DOM_MFC_CHG = 0d  ;
    public static Double OLD_MMFC_SLAB_1= 0d  ;
    public static Double OLD_MMFC_SLAB_2= 0d  ;
    public static Double OLD_MMFC_SLAB_3= 0d  ;
    public static Double OLD_MMFC_SLAB_4= 0d  ;
    public static Double OLD_MMFC_SLAB_5= 0d  ;
    public static String OLD_MD_MFC_CMP_FLAG  ;
    public static String OLD_Rate_UNIT_MFC ;
    public static String OLD_KWh_CON_KW_Flag  ;
    public static Double OLD_KWh_CON_KW= 0d  ;
    public static String OLD_MMFC_KVA_FLAG_SLAB_1 ;
    public static String OLD_MMFC_KVA_FLAG_SLAB_2 ;
    public static String OLD_MMFC_KVA_FLAG_SLAB_3 ;
    public static String OLD_MMFC_KVA_FLAG_SLAB_4 ;
    public static String OLD_MMFC_KVA_FLAG_SLAB_5 ;
    public static Double OLD_MMFC_URBAN_RATE_1= 0d  ;
    public static Double OLD_MMFC_URBAN_RATE_2= 0d  ;
    public static Double OLD_MMFC_URBAN_RATE_3= 0d  ;
    public static Double OLD_MMFC_URBAN_RATE_4= 0d  ;
    public static Double OLD_MMFC_URBAN_RATE_5= 0d  ;
    public static Double OLD_MMFC_RURAL_RATE_1= 0d  ;
    public static Double OLD_MMFC_RURAL_RATE_2= 0d  ;
    public static Double OLD_MMFC_RURAL_RATE_3= 0d  ;
    public static Double OLD_MMFC_RURAL_RATE_4= 0d  ;
    public static Double OLD_MMFC_RURAL_RATE_5= 0d  ;
    public static Double OLD_ADDNL_FIXED_CHARGE_1PH= 0d  ;
    public static Double OLD_ADDNL_FIXED_CHARGE_3PH= 0d  ;
    public static String OLD_FLAG_BPL_SUBSIDY_CODE  ;
    public static String OLD_FLAG_EC_MFC  ;
    public static Double OLD_MFC_SUBSIDY_FLAT= 0d  ;
    public static String OLD_FCA_SUBSIDY_FLAT;
    public static Double OLD_SUBSIDY_UNITS_SLAB_1= 0d  ;
    public static Double OLD_SUBSIDY_UNITS_SLAB_2= 0d  ;
    public static Double OLD_SUBSIDY_UNITS_SLAB_3= 0d  ;
    public static Double OLD_SUBSIDY_UNITS_SLAB_4= 0d  ;
    public static Double OLD_SUBSIDY_UNITS_SLAB_5= 0d  ;
    public static Double OLD_SUBSIDY_UNITS_SLAB_6= 0d  ;
    public static Double OLD_SUBSIDY_RATE_1 = 0d  ;
    public static Double OLD_SUBSIDY_RATE_2 = 0d  ;
    public static Double OLD_SUBSIDY_RATE_3 = 0d  ;
    public static Double OLD_SUBSIDY_RATE_4 = 0d  ;
    public static Double OLD_SUBSIDY_RATE_5 = 0d  ;
    public static Double OLD_SUBSIDY_RATE_6 = 0d  ;
    public static Double OLD_Below_30_DOM_MIN_CD_KW_ED= 0d  ;
    public static Double OLD_Below30_DOM_ED_Unit= 0d  ;
    public static Double OLD_Below30_DOM_ED_CHG= 0d  ;
    public static Double OLD_Below30_DOM_ED_CHG_Rate= 0d  ;
    public static Double OLD_ED_UNITS_SLAB_1= 0d  ;
    public static Double OLD_ED_UNITS_SLAB_2= 0d  ;
    public static Double OLD_ED_UNITS_SLAB_3= 0d  ;
    public static Double OLD_ED_UNITS_SLAB_4= 0d  ;
    public static Double OLD_ED_UNITS_SLAB_5= 0d  ;
    public static Double OLD_ED_URBAN_RATE_1= 0d  ;
    public static Double OLD_ED_URBAN_RATE_2= 0d  ;
    public static Double OLD_ED_URBAN_RATE_3= 0d  ;
    public static Double OLD_ED_URBAN_RATE_4= 0d  ;
    public static Double OLD_ED_URBAN_RATE_5= 0d  ;
    public static Double OLD_ED_RURAL_RATE_1= 0d  ;
    public static Double OLD_ED_RURAL_RATE_2= 0d  ;
    public static Double OLD_ED_RURAL_RATE_3= 0d  ;
    public static Double OLD_ED_RURAL_RATE_4= 0d  ;
    public static Double OLD_ED_RURAL_RATE_5= 0d  ;
    public static Double OLD_ED_PER_RATE_1= 0d  ;
    public static Double OLD_ED_PER_RATE_2= 0d  ;
    public static Double OLD_ED_PER_RATE_3= 0d  ;
    public static Double OLD_ED_PER_RATE_4= 0d  ;
    public static Double OLD_ED_PER_RATE_5= 0d  ;
    public static Double OLD_FCA_Q1= 0d  ;
    public static Double OLD_FCA_Q2= 0d  ;
    public static Double OLD_FCA_Q3= 0d  ;
    public static Double OLD_FCA_Q4= 0d  ;
    public static Double OLD_PREPAID_REBATE= 0d  ;
    public static Double OLD_ISI_INC_FLAG= 0d  ;
    public static Double OLD_ISI_MOTOR_INCENTIVE_TYPE_1= 0d  ;
    public static Double OLD_ISI_MOTOR_INCENTIVE_TYPE_2= 0d  ;
    public static Double OLD_ISI_MOTOR_INCENTIVE_TYPE_3= 0d  ;
    public static Double OLD_MIN_DPS_BILL_AMT= 0d  ;
    public static Double OLD_DPS_MIN_AMT_Below_500= 0d  ;
    public static Double OLD_DPS_MIN_AMT_Above_500= 0d  ;
    public static String OLD_DPS_FLAG_PERCENTAGE ;
    public static Double OLD_DPS_MP= 0d  ;
    public static Double OLD_ADV_PAY_REBATE_PERCENT= 0d  ;
    public static Double OLD_INC_PMPT_PAY_PERCENT= 0d  ;
    public static Double OLD_OL_REBATE_PERCENT= 0d  ;
    public static Double OLD_LF_INC_SLAB_1= 0d  ;
    public static Double OLD_LF_INC_SLAB_2= 0d  ;
    public static Double OLD_LF_INC_SLAB_3= 0d  ;
    public static Double OLD_LF_INC_RATE_1= 0d  ;
    public static Double OLD_LF_INC_RATE_2= 0d  ;
    public static Double OLD_LF_INC_RATE_3= 0d  ;
    public static Double OLD_PF_INC_SLAB_1= 0d  ;
    public static Double OLD_PF_INC_SLAB_2= 0d  ;
    public static Double OLD_PF_INC_RATE_1= 0d  ;
    public static Double OLD_PF_INC_RATE_2= 0d  ;
    public static Double OLD_PF_PEN_SLAB_1= 0d  ;
    public static Double OLD_PF_PEN_SLAB_2= 0d  ;
    public static Double OLD_PF_PEN_RATE_1= 0d  ;
    public static Double OLD_PF_PEN_RATE_2= 0d  ;
    public static Double OLD_PF_PEN_SLAB2_ADDL_PERCENT= 0d  ;
    public static Double OLD_PF_PEN_MAX_CAP_PER= 0d  ;
    public static Double OLD_WL_SLAB= 0d  ;
    public static Double OLD_WL_RATE= 0d  ;
    public static Double OLD_Emp_Rebate= 0d  ;
    public static String OLD_FLG_FIXED_UNIT_SUBSIDY ;
    public static Double OLD_Overdrawl_Slab1 =0d  ;
    public static Double OLD_Overdrawl_Slab2 =0d   ;
    public static Double OLD_Overdrawl_Slab3 =0d   ;
    public static Double OLD_Overdrawl_Rate1 =0d   ;
    public static Double OLD_Overdrawl_Rate2 =0d   ;
    public static Double OLD_Overdrawl_Rate3 =0d   ;
    public static String OLD_EC_Flag           ;
    public static String OLD_ED_Flag           ;
    public static String OLD_Tariff_URBAN           ;
    public static String OLD_Tariff_RURAL           ;
    public static String OLD_MAX_ALLOWABLE_CONSUMPTION           ;
    public static String OLD_PF_APPLICABLE           ;
    public static String OLD_PF_INC_APPLICABLE           ;
    public static String OLD_CAP_CHRG_APPLICABLE           ;
    public static String OLD_FULL_SUBSIDY_FLAG           ;
    public static String OLD_IND_VALIDATION          ;
    public static String OLD_BPL_VALIDATION          ;
    public static String OLD_JBP_VALIDATION          ;
}
