package com.fedco.mbc.model;

public class Structmetering {

    public static String 	 CONSUMERNO 			;
    public static String 	 OLDCONSUMERNO 	     	;
    public static String 	 TARIFFCODE 	     	;
    public static String 	 METERDEVICESERIALNO 	;
    public static String 	 NAME 	             	;
    public static String 	 ADDRESS 	         	;
    public static String 	 CYCLE 	             	;
    public static String 	 ROUTENO 	         	;
    public static String 	 DIVISION 	         	;
    public static String 	 SUBDIVISION 	     	;
    public static String	 SECTION 	         	;
    public static String 	 BILLMONTH 	         	;
    public static String 	 METERREADINGDATE 	 	;
    public static String	 CURRENTMETERSTATUS 	;
    public static String 	 NORMALKWH 	         	;
    public static String 	 NORMALKVAH 	     	;
    public static String 	 NORMALKVARH 	     	;
    public static String 	 NORMALMD 	         	;
    public static String 	 NORMALMDUNIT 	     	;
    public static String 	 PEAKKWH 	         	;
    public static String	 PEAKKVAH 	         	;
    public static String	 PEAKKHARH 	         	;
    public static String	 PEAKMD 	         	;
    public static String	 PEAKMDUNIT 	     	;
    public static String	 OFFPEAKKWH 	     	;
    public static String	 OFFPEAKKVAH 	     	;
    public static String	 OFFPEAKKHARH 	     	;
    public static String	 OFFPEAKMD 	         	;
    public static String	 OFFPEAKMDUNIT 	     	;
    public static String	 RIFLAG              	;
    public static String	 OUTTERBOXSEAL  		;
    public static String	 INNERBOXSEAL  			;
    public static String	 OPTICALSEAL  			;
    public static String	 MDBUTTONSEAL  			;
    public static String	 CUMULATIVEMD  			;
    public static String	 KWH3CON  				;
    public static String	 KWHLASTMONCON  				;
    public static String	 MD3CON  				;
    public static String	 MDLASTMONCON  				;
    public static String	 OFFPEAKKWH3CON  			;
    public static String	 OFFPEAKKWHLASTMONCON  			;
    public static String	 MOB_NO  				;
    public static String	 EMAIL  				;
    public static String	 METERREPLACE  			;
    public static String	 NSC  				    ;
    public static String	 MF  				    ;
    public static String     KVAH3CON               ;
    public static String     KVAHLASTMONCON               ;
    public static String     LOAD                   ;
    public static String     LOADUNITS              ;
    public static String     METERDIGIT             ;
    public static String     DIVCODE                ;
    public static String     SUBDIVCODE             ;
    public static String     SECCODE                ;
    public static String     PREVPAYMENT            ;
    public static String     PANNO                  ;
    public static String     CESUDIV             ;
    public static String     CESUSUBDIV             ;
    public static String     CESUSEC             ;

}
